### PR TITLE
Upgrating `analyzer` version (and fix bugs caused by upgrading)

### PR DESCRIPTION
**Pull request by fzyzcjy**
The `mobx.dart` requires `analyzer: '>=0.38.5 <0.40.0'`, while this package forces to be lower. Thus, the two cannot be installed without conflict. So I update the version. In addition, there is a bug when updating it, so I also fix two little lines.

### CODE REVIEW

**Comment by rrousselGit** [comment]
Thanks!

Do you mind upgrading the version used in the `code_gen_tester` folder too? Otherwise, the CI will not pass

**Comment by fzyzcjy** [comment]
Done! Waiting for CI now

**Comment by fzyzcjy** [comment]
Wait a minute, need more changes...

**Comment by fzyzcjy** [comment]
The `dart_style` `>=1.2.4 <1.2.5` conflicts. So I change to `^1.2.4`, is it OK? (It seems that, by semantic versioning, it should not break anything)

**Comment by fzyzcjy** [comment]
Hmmmm... This problem existed before...? Since the current master is "failing" not "passing" https://travis-ci.org/rrousselGit/functional_widget/jobs/651796953#L372

**Comment by rrousselGit** [comment]
Indeed, it seems like newer versions introduced a bunch of extra lints.

I'll close this PR and fix everything myself

**Comment by fzyzcjy** [comment]
OK

**Pull request closed without merging**
